"""Update usersubscription

Revision ID: dfa36ccfa50d
Revises: 954a3bdfd5f3
Create Date: 2025-09-13 12:20:59.241297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa36ccfa50d'
down_revision: Union[str, Sequence[str], None] = '954a3bdfd5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_subscriptions', sa.Column('stripe_subscription_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_subscriptions', 'stripe_subscription_id')
    # ### end Alembic commands ###
